# Language setting
language: python

# Version number
python:
  - 2.7

build:
  ci:
    - python --version
    
resources:

  - name: stabledockercliconfig
    type: cliConfig
    integration: "docker"
    
  - name: version-resource
    type: version
    seed:
      versionName: "0.0.1-beta"

  - name: stablerepo
    type: gitRepo
    integration: github
    pointer:
      sourceName: ami-stable/sample-pipelines
      branch: master    
        
jobs:
  - name: stablesimplerunsh
    type: runSh
    steps:
      - IN: stablerepo
      - TASK:
        - script: ls
        #- script: ./GET/infra-repo/infra-repo/provision.sh
    always:
      - script: echo "This works on_always"
